投稿カテゴリの設定が適用されない問題を修正
gnexltd/push7-wp-plugin pull request #63
Opened 2019-10-25 02:02 UTC by nkpoid

## WHAT 
same as title

2019-10-28 08:00 UTC, a-r-g-v commented
@nkpoid CI を修正いただけませんか

2019-10-28 10:32 UTC, a-r-g-v requested changes

2019-10-28 10:32 UTC, a-r-g-v commented on classes/push7-post.php
> +    $post_id = $this->get_post_id($post);
なぜ `$post_id` の再取得をしているの しているのでしょうか？

2019-10-28 10:32 UTC, a-r-g-v commented on classes/push7-post.php
> +    // 通常投稿の場合のみカテゴリチェックを行う
このコメントはなくて良いと思います。下の文と言っていることが同じだと思うからです。
（言及するべきは、 「なぜ通常投稿の場合のみカテゴリチェックを行うのか？」だと思います）

2019-10-28 10:32 UTC, a-r-g-v commented on setting.php
> -                  if($post_type == "post") continue;
なぜ この continue 削除されてますか？

2019-10-28 10:32 UTC, a-r-g-v commented on setting.php
> +                    <?= $post_type === 'post' ? 'post(通常の投稿)' : $post_type; ?>
`==` から `===` に変更してもよいのでしょうか？

2019-10-28 10:32 UTC, a-r-g-v commented on classes/push7-post.php
> +    if ($post_type === 'post' && $this->check_ignored_category($post_id)) return;
`==` ではなく、`===` に変更してもよいのでしょうか？

2019-10-28 10:52 UTC, nkpoid commented on classes/push7-post.php
> +    $post_id = $this->get_post_id($post);
これは頭ついてませんでした

2019-10-28 10:52 UTC, nkpoid commented on classes/push7-post.php
> +    // 通常投稿の場合のみカテゴリチェックを行う
理由を明確に修正します

2019-10-28 10:52 UTC, nkpoid commented on classes/push7-post.php
> +    if ($post_type === 'post' && $this->check_ignored_category($post_id)) return;
はい

2019-10-28 10:52 UTC, nkpoid commented on setting.php
> -                  if($post_type == "post") continue;
この処理によって、投稿タイプが通常のものに対して一括の通知無効処理ができなくなっており不便だと感じたためです

2019-10-28 10:52 UTC, nkpoid commented on setting.php
> +                    <?= $post_type === 'post' ? 'post(通常の投稿)' : $post_type; ?>
はい

2019-10-28 11:12 UTC, a-r-g-v requested changes
CIの修正をお願いします（コードはLGTMです）

2019-10-28 11:14 UTC, a-r-g-v commented on classes/push7-post.php
> +    return $setting === 'false' || $setting === '';
get_option で空文字列が返ってくる原因って検討ついてますか？

2019-11-02 23:29 UTC, a-r-g-v approved these changes

2019-11-02 23:30 UTC, merged